## Using Actions with Filament

The `make:action` command generates action classes that work seamlessly with Filament v4 and v5 projects. Action classes are ideal for encapsulating business logic that Filament components can call.

### Actions in Filament Context

While Filament has its own "Action" concept (UI actions like buttons and modals), the action classes generated by `make:action` serve a different purpose - they encapsulate **business logic** that can be called from anywhere, including Filament resources, pages, and widgets.

### Common Patterns

#### Using Actions in Filament Resources

@verbatim
<code-snippet name="Action class for Filament resource" lang="php">
<?php

namespace App\Actions;

use App\Models\User;

class ActivateUser
{
    public function handle(User $user): User
    {
        $user->update(['is_active' => true]);

        // Additional logic: send notification, log activity, etc.

        return $user;
    }
}
</code-snippet>
@endverbatim

@verbatim
<code-snippet name="Calling action from Filament table action" lang="php">
use App\Actions\ActivateUser;
use Filament\Tables\Actions\Action;

Action::make('activate')
    ->action(function (User $record, ActivateUser $activateUser) {
        $activateUser->handle($record);
    })
    ->requiresConfirmation()
</code-snippet>
@endverbatim

#### Using Actions in Filament Pages

@verbatim
<code-snippet name="Action in Filament page" lang="php">
use App\Actions\GenerateReport;

class Dashboard extends Page
{
    public function generateMonthlyReport(GenerateReport $action)
    {
        $report = $action->handle(now()->startOfMonth(), now()->endOfMonth());

        $this->dispatch('report-generated', reportId: $report->id);
    }
}
</code-snippet>
@endverbatim

#### Using Actions in Filament Form Submissions

@verbatim
<code-snippet name="Action in Filament create/edit resource" lang="php">
use App\Actions\CreateUser;

class CreateUserResource extends CreateRecord
{
    protected function handleRecordCreation(array $data): Model
    {
        return app(CreateUser::class)->handle($data);
    }
}
</code-snippet>
@endverbatim

### Best Practices for Filament Projects

- Keep Filament UI Actions (buttons, modals) thin - delegate business logic to action classes
- Use dependency injection in action constructors for services needed by the action
- Action classes can be easily tested in isolation, independent of Filament UI
- Share action classes between Filament admin panel and API endpoints for consistency
